# minimal override example
include: package:very_good_analysis/analysis_options.yaml

analyzer:
  exclude:
    - lib/l10n/gen/*
  strong-mode:
    implicit-casts: true
    implicit-dynamic: true

linter:
  rules:
    public_member_api_docs: false
    # optionally disable some very_good rules you find noisy:
    avoid_returning_null_for_future: false
