// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmMpYQui8aGL1CX3493oQg4BkDzTCYi0U',
    appId: '1:871770676449:web:c8d48650496613aac96ba0',
    messagingSenderId: '871770676449',
    projectId: 'brosisus-f3ce9',
    authDomain: 'brosisus-f3ce9.firebaseapp.com',
    storageBucket: 'brosisus-f3ce9.firebasestorage.app',
    measurementId: 'G-RZZ2TZRHNM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOm-pt10gOxu7q7bo0ICwLMk1o2flElNo',
    appId: '1:871770676449:android:c0fad9a6f7493582c96ba0',
    messagingSenderId: '871770676449',
    projectId: 'brosisus-f3ce9',
    storageBucket: 'brosisus-f3ce9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCb4MzhMcree4mVvE1nboBaj-Man7WlVRA',
    appId: '1:871770676449:ios:693ee6f1a9acde08c96ba0',
    messagingSenderId: '871770676449',
    projectId: 'brosisus-f3ce9',
    storageBucket: 'brosisus-f3ce9.firebasestorage.app',
    iosBundleId: 'com.example.start',
  );

}