// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDg7JuspyN-8CBEKHAvHajeSa52vtK2mk0',
    appId: '1:129605762315:web:db00ff441be2b99082360e',
    messagingSenderId: '129605762315',
    projectId: 'dadadu-flutter',
    authDomain: 'dadadu-flutter.firebaseapp.com',
    storageBucket: 'dadadu-flutter.firebasestorage.app',
    measurementId: 'G-SM56W7T9R1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCoJNSb_RwEUuVME2u1mVuSz8fyQYr0QFI',
    appId: '1:129605762315:android:79ad126b43150d4b82360e',
    messagingSenderId: '129605762315',
    projectId: 'dadadu-flutter',
    storageBucket: 'dadadu-flutter.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCc2glXx3UaXwYymLl95Z7bPoxgxwenKY',
    appId: '1:129605762315:ios:974abe58ffbddacc82360e',
    messagingSenderId: '129605762315',
    projectId: 'dadadu-flutter',
    storageBucket: 'dadadu-flutter.firebasestorage.app',
    iosBundleId: 'com.example.start',
  );
}
